## NumPy

### Creating numpy arrays

In [2]:
# from list or tuple
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# using build-in functions
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [10]:
a = np.linspace(0, 1, 5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
a = np.random.rand(2, 3)
a

array([[0.39233558, 0.45666642, 0.35967731],
       [0.4038544 , 0.62777086, 0.50275395]])

### Operations on numpy arrays

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])

In [4]:
a = np.array([1, 2, 3])

b = np.sin(a)
print(b) 

c = np.log(a)
print(c)

[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])

sum_all = np.sum(a)
print(sum_all) 

# axis=0 is the first dimenstion (rows)
# sum all columns
sum_axis0 = np.sum(a, axis=0)
print(sum_axis0) 

# axis=1 are the columns
# sum all rows
sum_axis1 = np.sum(a, axis=1)
print(sum_axis1) 

21
[5 7 9]
[ 6 15]


In [ ]:
# Exercise: can you get the mean instead of the sum?

### Indexing and Slicing

In [8]:
# 1D Array Indexing
a = np.array([10, 20, 30, 40, 50])
print(a[0]) 
print(a[2]) 
print(a[-1]) # last element

10
30
50


In [9]:
# 2D Array Indexing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 0])  
print(a[1, 2]) 
print(a[-1, -1]) 

1
6
9


In [11]:
# 1D slicing
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])  # between 1 and 4
print(a[:3])   # before 3
print(a[2:]) # after 2

[20 30 40]
[10 20 30]
[30 40 50]


In [13]:
# 2D slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[:2, 1:3]) 
print(a[1:, :2]) 

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


### Advanced indexing

In [15]:
# elements that meet a condition
a = np.array([10, 20, 30, 40, 50])
print(a[a > 25])

[30 40 50]


In [16]:
# access specific elements
a = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print(a[indices])

[10 30 50]


In [17]:
# mixing indexing and slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[[0, 2], 1:3])

[[2 3]
 [8 9]]


### Modifying Arrays with Indexing and Slicing

In [19]:
a = np.array([10, 20, 30, 40, 50])
a[1] = 25
a

array([10, 25, 30, 40, 50])

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[1:, :2] = 0
print(a)

[[1 2 3]
 [0 0 6]
 [0 0 9]]
